services:
  chatservice:
    build: .
    container_name: chatservice_app
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
      - "50052:50051"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
